### ISSUE TITLE
[BUG] Can not import `.wasm` (by @prisma/client)

### ISSUE THREAD

**Issue by mizchi** [opennextjs/opennextjs-cloudflare#139]
### Describe the bug

Opennext and `@prisma/client/wasm` do not work by  import `*.wasm`.

Prisma does not work on opennext.

```bash
$ npm install prisma @prisma/client -D
$ npx prisma --init
# ... edit to use @prisma/client/wasm
$ npx next build
$ npx cloudflare # it works yet
$ wrangler deploy # fail at wrangler's  esbuild
```

```ts
   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
PrismaClientKnownRequestError: 
Invalid `prisma.post.findMany()` invocation:


Unknown file extension ".wasm" for /home/mizchi/mizchi/next-memo/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/.prisma/client/query_engine_bg.wasm
    at dr.handleRequestError (/home/mizchi/mizchi/next-memo/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/wasm.js:21:7567)
    at dr.handleAndLogRequestError (/home/mizchi/mizchi/next-memo/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/wasm.js:21:6875)
    at dr.request (/home/mizchi/mizchi/next-memo/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/wasm.js:21:6565)
    at async u (/home/mizchi/mizchi/next-memo/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/wasm.js:30:9560)
    at async I (/home/mizchi/mizchi/next-memo/.next/server/app/page.js:1:39579)
Export encountered an error on /page: /, exiting the build.
 ⨯ Static worker exited with code: 1 and signal: null
node:internal/errors:983
  const err = new Error(message);
```

Vite and webpack can handle it but wrangler's  esbuild & workerd

### Steps to reproduce

- setup prisma 
- import `@prisma/client/wasm`

```ts
import { PrismaClient } from "@prisma/client/wasm";
import { PrismaD1 } from "@prisma/adapter-d1";
import { getCloudflareContext } from "@opennextjs/cloudflare";

export interface Env {
  DB: D1Database;
}

export async function getPrismaClient() {
  try {
    const ctx: any = await getCloudflareContext();
    return new PrismaClient({ adapter: new PrismaD1(ctx.env.DB) });
  } catch (error) {
    console.error("Error getting Prisma client", error);
    throw error;
  }
}
```

Deploy ``

### Expected behavior

`@prisma/client` works on opennext.

### @opennextjs/cloudflare version

0.2.1

### Node.js version

22.x

### Wrangler version

3.88.0

### next info output

```shell
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Tue Nov 5 00:21:55 UTC 2024
  Available memory (MB): 64163
  Available CPU cores: 16
Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: N/A
  pnpm: 9.9.0
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: 15.0.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```
```


### Additional context

This `.wasm`  import style is generated by Rust's `wasm-pack`

**Comment by wmadden** [comment]
Hi @mizchi, it looks like your issue is caused by `wrangler` which by default will delete any `.wasm` files when you publish.

Others [have solved this problem](https://community.cloudflare.com/t/how-to-include-wasm-file-binding-with-wranger-publish/143232/2) by adding configuration to `wrangler.toml` - [read more about it here](https://blog.cloudflare.com/cloudflare-worker-with-webassembly-and-haskell/).

**Comment by vicb** [comment]
Good point, can you try adding [`find_additional_modules=true`](warn if there are node imports (if not in v1 mode)) in your `wrangler.toml`?
It will add the the `.wasm` files as additional modules.

**Comment by mizchi** [comment]
thx @vicb @wmadden 

I used those links to verify this by rewriting `node_moudules` directly at hand.

First I needed to examine the prisma code generation and runtime steps.

- Code generation process
  - Running `npx prisma generate` executes `@prisma/client/generator-build/index.js` by prisma's CLI, and `@prisma/client/.prisma/client/*` generates Assemble the client code.
  - Copy `@prisma/client/.prisma/client/query_engine_wasm.bg` according to Prisma's generator(postgres/mysql/sqlite)
- Runtime
  - `import {PrismaClient} from @prisma/client/wasm` resolves `@prisma/client/.prisma/client/wasm.js`(cjs)
  - Initialize `query_engine_bg.wasm` as binary by fs.readFileSync with `return new WebAssembly.Module(queryEngineWasmFileBytes)`.

https://github.com/prisma/prisma/blob/b6fe641510af621b30eb183076d98b61cdfe9c3d/packages/client/src/generation/utils/buildGetQueryEngineWasmModule.ts#L13-L21

I found some problems here.

- According to [this document](https://developers.cloudflare.com/workers/wrangler/bundling/) workers need to initialize wasm in global scope before the fetch handler
- prisma/client resolves wasm as cjs, so imports in global scope cannot resolve it
- The wrangler `wasm_modules` cannot be used in ESM mode. But the output of opennext always expects ESM
- Webpack: opennext pre-processes next as webpack first, so .wasm cannot be resolved at this stage. you need to delay resolving `.wasm` until wrangler esbuild.

----

This is my trial and error. It hasn't completely worked yet, but it worked on hand to the point where it bypasses the initialization of wasm.

First, in `next.config.js`, prevent .wasm from loading.

``js
    config.plugins.push(
      new webpack.IgnorePlugin({
        contextRegExp: /\\.wasm$/,
        resourceRegExp: /\\.wasm$/, }
      })
    );
```

At prisma/client/wasm runtime, modify the code generator to resolve from global variables.

```js
diff --git a/generator-build/index.js b/generator-build/index.js
index f0adad1914bb059450d36d8df69acd57f9c95750..056bf25d709c0ca12f0b748d58f2156f54fadec9 100644
--- a/generator-build/index.js
+++ b/generator-build/index.js
@@ -7753,10 +7753,7 @@ function buildQueryEngineWasmModule(wasm, copyEngine, runtimeNameJs) {
     return `config.engineWasm = {
       getRuntime: () => require('. /query_engine_bg.js'),.
       getQueryEngineWasmModule: async () => {
- const queryEngineWasmFilePath = require('path').join(config.dirname, 'query_engine_bg.wasm')
- const queryEngineWasmFileBytes = require('fs').readFileSync(queryEngineWasmFilePath)
-fs'.      
- return new WebAssembly.Module(queryEngineWasmFileBytes)
+ return __PRISMA_BINARY;
       }
     }`;
   }
@@ -7764,9 +7761,7 @@ function buildQueryEngineWasmModule(wasm, copyEngine, runtimeNameJs) {
     return `config.engineWasm = {
   getRuntime: () => require('. /query_engine_bg.js'),.
   getQueryEngineWasmModule: async () => {
- const loader = (await import('#wasm-engine-loader')).default
- const engine = (await loader).default
- return engine 
+ return __PRISMA_BINARY;
   }
 }`;
   }
```

With this in place, copy `. /query_engine_bg.wasm` directly down into .workers-next and insert the following code into the `.workers-next/index.mjs` entry point for workers.

```js
import wasm from “. /query_engine_bg.wasm”;
globalThis.__PRISMA_BINARY = await WebAssembly.instantiate(wasm);
// ...original
```

This should now work, at least on the Workers runtime.

However, we could not verify that this actually works. The reason is that it fails in the prerender phase of the Next App Router. The prerender executes `.next` directly in node.js, so on the contrary, it can no longer resolve the `__PRISMA_BINARY` in this patch.

There may be a better way. I will experiment some more.

**Comment by vicb** [comment]
Thanks for the detailed analysis!

**Comment by Yesterday17** [comment]
I managed to use and deploy my app using `prisma` by following the steps above, but with a slightly different change:

```ts
import wasm from ". /query_engine_bg.wasm";
globalThis.__PRISMA_BINARY = wasm
```

And `prisma` will do the `WebAssembly.instantiate` step in its code.

**Comment by mizchi** [comment]
I deal with the issue on a regular basis.

Prisma itself is currently being rewritten from Rust to TypeScript.

https://www.prisma.io/blog/rust-to-typescript-update-boosting-prisma-orm-performance

This will likely circumvent this issue.

We're enabling an experimental client based on benchmarks.

https://github.com/prisma/query-compiler-benchmarks/tree/main/benches/prisma-pg-qc

## Setup

```:.env
DATABASE_URL="..."
PRISMA_UNSTABLE_CLIENT_ENGINE_TYPE=true
```

schema.prisma

```ts
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
  engineType      = "client"
}
```

Run with postgres on node.js

```ts
import { PrismaClient } from "@prisma/client;
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";

const connectionString = process.env.DATABASE_URL ?? "";
const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });
await prisma.$connect();

try {
  const users = await prisma.user.findMany();
  console.log("users", users);
} catch (error) {
  console.error("error", error);
} finally {
  await prisma.$disconnect().catch(console.error);
  process.exit(0);
}
```

This runtime allowed me to avoid using wasm, at least for postgres on localhost docker.

However, it didn't work with anything other than postgres.

I haven't tried it yet, but it's likely to work on opennext if you use prisma/adapte-pg-worker.

**Comment by mizchi** [comment]
Prisma (no-rust, 6.7.0 preview) works with OpenNext!

It uses with `queryCompiler` and `driverAdapters`.

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["queryCompiler", "driverAdapters"]
  output   = "../src/generated/prisma"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// sample model
model User {
  id        String   @id @default(cuid())
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

Generate prisma/client without runtime engines.

```bash
$ npx prisma generate --no-engine
$ npx prisma migrate dev
```

(I tried with https://www.prisma.io/postgres)

```ts
// src/app/page.tsx
import { PrismaClient } from "../generated/prisma";
const prisma = new PrismaClient();

export default async function Page() {
  const users = await prisma.user.findFirst({});
  return (
    <div>
      <pre>{JSON.stringify(users, null, 2)}</pre>
    </div>
  );
}
```

This doesn't solve the issue of wasm-pack generating code that can't be loaded, but it seems to solve the problem with prisma.

**Comment by mizchi** [comment]
I reported prisma/client/runtime/library does not work on workerd but it relates opennext bundle process about `import.meta.url`

https://github.com/prisma/prisma/issues/27098

**Comment by conico974** [comment]
@mizchi This should be fixed in [1.0.0](https://github.com/opennextjs/opennextjs-cloudflare/releases/tag/%40opennextjs%2Fcloudflare%401.0.0)

Also see the docs for prisma here https://opennext.js.org/cloudflare/howtos/db#prisma-orm

**Comment by mizchi** [comment]
@conico974 

I overlooked that prisma documentation. Thanks!

I tried v1.0.0 and the `import.meta.url` issue seems to be resolved.

Unfortunately, it seems that I can't use that method when I enable `queryCompiler`.

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["queryCompiler", "driverAdapters"]
  // output   = "../src/generated/prisma"
}
```

```bash
$ npx prisma generate --no-engine
Warning: You did not specify an output path for your `generator` in schema.prisma. This behavior is deprecated and will no longer be supported in Prisma 7.0.0. To learn more visit https://pris.ly/cli/output-path
```

It seems that specifying output will be required in 7.0.0, but the experimental queryCompiler may already require it.

**Comment by justin-free** [comment]
Hit this exact wall tonight with `@prisma/client` 6.19.3's `engineType = "client"` (the driver-adapter architecture, no native engine binary) on `@opennextjs/cloudflare` 1.20.2, Next.js 15.5.23, plain webpack (not Turbopack) — some findings that might help narrow this down.

**The starting error**, with no wasm handling at all (Prisma's default output decodes its query-compiler wasm from an embedded base64 string and calls `new WebAssembly.Module()` on the bytes at runtime):

```
WebAssembly.Module(): Wasm code generation disallowed by embedder
```

Expected — Workers disallows runtime wasm compilation outright, no compat flag around it. The fix has to be a real build-time `.wasm` module import.

**What I tried, and where each one broke:**

1. `experiments.asyncWebAssembly: true` in webpack config — builds fine, but generates Node.js-style `fs.readFileSync` + runtime-compile glue (correct for a normal Node deploy, wrong for Workers). Fails at deploy: `no such file or directory, readAll '/bundle/static/wasm/<hash>.wasm'`.

2. Marking `.wasm` external in webpack (`config.externals`) — webpack resolves the relative import to an absolute path *before* the externals callback runs. Since the import is reachable from ~40+ API routes (Next's per-route webpack chunking), each route tries to resolve/copy the file relative to its own per-route output dir independently — dozens of broken, duplicated absolute paths, one `next build` error per route.

3. A `wasm_modules` legacy Wrangler binding (bypassing import resolution entirely, declaring the file directly in `wrangler.jsonc`) — rejected outright by workerd for ES-module-format Workers: `"Wasm bindings are not allowed in modules-based scripts. Use Wasm modules instead."` Not just discouraged — a hard runtime error at Worker startup.

4. `/* webpackIgnore: true */` on the dynamic import — the closest to working. Webpack leaves the import completely untouched. **But Next.js's own output-file-tracing pass finds and relocates the file anyway** (independent of webpack's bundling, doesn't respect `webpackIgnore`), copying it to `.next/server/<basename>.wasm` and rewriting the reference to an *absolute* path pointing there. Wrangler's own `wrangler-module-collector` esbuild plugin then chokes on that absolute path:

```
ENOENT: no such file or directory, open '<repo>/.open-next/server-functions/default<repo>/.open-next/server-functions/default/.next/server/query_compiler_bg.postgresql.wasm'
```

That's a doubled path — reading Wrangler's collector source (`wrangler-dist/cli.js`, the `wrangler-module-collector` plugin), it does `path.join(args.resolveDir, cleanedPath)` without checking whether `cleanedPath` is already absolute, and its two fallback resolution attempts (esbuild's own `resolve()`, then the `resolve` npm package) both apparently fail silently for this case rather than correcting it. Reproduced identically on both Windows and Cloudflare's actual Linux build runner, so it's not platform-specific — genuinely looks like a real bug in that plugin's absolute-path handling, separate from (upstream of) whatever OpenNext does.

Ended up going with a `scripts/patch-prisma-wasm.mjs` postinstall step that rewrites the generated Prisma client to reference a pre-extracted `.wasm` file — but haven't found a way to get it through Wrangler's bundler cleanly yet given the file-tracing relocation. Happy to share the full repro (a minimal Next.js + `@prisma/adapter-neon` + `engineType=client` + OpenNext Cloudflare project) if useful for reproducing outside our actual codebase.
